openapi: 3.0.1
info:
  title: FPM Pattern Query Manager
  description: 'API for Federated Process Mining Pattern Query Manager'
  termsOfService: http://swagger.io/terms/
  contact:
    email: javirojo@unex.es
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://localhost/docs
servers:
- url: https://localhost/
tags:
- name: query
  description: Operate with queries
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /request:
    get:
      tags:
      - query
      summary: Request for traces that met the pattern sought
      parameters:
        - in: query
          name: pattern
          schema:
            type: string
          required: true
          description: Pattern that must be met in the traces to be sended later.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryRequest'
            application/xml:
              schema:
                $ref: '#/components/schemas/QueryRequest'
        401:
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
            application/xml:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        500:
          description: "Internal Error"
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ServerError'
        x-codegen-request-body-name: body
      
components:
  schemas:
    QueryRequest:
      type: object
      properties:
        pattern:
          type: string
        ok:
          type: boolean
          default: true
      xml:
        name: QueryRequest   
    
    Unauthorized:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        status:
          type: number
          format: integer
        reason:
          type: string
      xml:
        name: Unauthorized 
        
    ServerError:
      type: object
      properties:
        pattern:
          type: string
        ok:
          type: boolean
          default: false
      xml:
        name: ServerError   
        
